export const COMMAND_MASK = 0x000000ff;
export const THREAD_MASK = 0x0000ff00;
export const NEEDLE_MASK = 0x00ff0000;
export const ORDER_MASK = 0xff000000;

export enum Command {
  NO_COMMAND = -1,
  STITCH = 0,
  JUMP = 1,
  TRIM = 2,
  STOP = 3,
  END = 4,
  COLOUR_CHANGE = 5,
  NEEDLE_SET = 9,
  SEQUIN_MODE = 6,
  SEQUIN_EJECT = 7,
  SLOW = 0xb,
  FAST = 0xc,
  SET_CHANGE_SEQUENCE = 0x10,
  SEW_TO = 0xb0,
  NEEDLE_AT = 0xb1,
  STITCH_BREAK = 0xe0,
  SEQUENCE_BREAK = 0xe1,
  COLOUR_BREAK = 0xe2,
  TIE_ON = 0xe4,
  TIE_OFF = 0xe5,
  FRAME_EJECT = 0xe9,

  MATRIX_TRANSLATE = 0xc0,
  MATRIX_SCALE_ORIGIN = 0xc1,
  MATRIX_ROTATE_ORIGIN = 0xc2,
  MATRIX_SCALE = 0xc4,
  MATRIX_ROTATE = 0xc5,
  MATRIX_RESET = 0xc3,

  OPTION_MAX_STITCH_LENGTH = 0xd5,
  OPTION_MAX_JUMP_LENGTH = 0xd6,
  OPTION_EXPLICIT_TRIM = 0xd7,
  OPTION_IMPLICIT_TRIM = 0xd8,

  CONTINGENCY_TIE_ON_NONE = 0xd3,
  CONTINGENCY_TIE_ON_THREE_SMALL = 0xd1,

  CONTINGENCY_TIE_OFF_NONE = 0xd4,
  CONTINGENCY_TIE_OFF_THREE_SMALL = 0xd2,

  CONTINGENCY_LONG_STITCH_NONE = 0xf0,
  CONTINGENCY_LONG_STITCH_JUMP_NEEDLE = 0xf1,
  CONTINGENCY_LONG_STITCH_SEW_TO = 0xf2,

  CONTINGENCY_SEQUIN_UTILIZE = 0xf5,
  CONTINGENCY_SEQUIN_JUMP = 0xf6,
  CONTINGENCY_SEQUIN_STITCH = 0xf7,
  CONTINGENCY_SEQUIN_REMOVE = 0xf8
}
